name: Smoke Test - Combined (Flights + Hotels)

on:
  workflow_dispatch:

jobs:
  combined:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run combined smoke
        working-directory: agent
        env:
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          AMADEUS_BASE: https://test.api.amadeus.com
        run: |
          python smoke_test_combined.py
