name: Smoke Test – Kiwi

on:
  workflow_dispatch:
    inputs:
      origin:
        description: "Departure IATA"
        required: false
        default: "EMA"
      destination:
        description: "Arrival IATA"
        required: false
        default: "ALC"
      startDate:
        description: "Start date (YYYY-MM-DD)"
        required: false
        default: "2025-08-25"
      nights:
        description: "Nights"
        required: false
        default: "4"
      adults:
        description: "Adults"
        required: false
        default: "2"
      children:
        description: "Children"
        required: false
        default: "0"

jobs:
  kiwi-smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Kiwi smoke test
        env:
          RAPIDAPI_KIWI_KEY: ${{ secrets.RAPIDAPI_KIWI_KEY }}
        run: |
          python agent/smoke_test_kiwi.py \
            --origin "${{ github.event.inputs.origin }}" \
            --destination "${{ github.event.inputs.destination }}" \
            --startDate "${{ github.event.inputs.startDate }}" \
            --nights "${{ github.event.inputs.nights }}" \
            --adults "${{ github.event.inputs.adults }}" \
            --children "${{ github.event.inputs.children }}"
