name: Smoke Test (Kiwi + Amadeus)

on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke test
        env:
          RAPIDAPI_KIWI_KEY: ${{ secrets.RAPIDAPI_KIWI_KEY }}
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
        run: |
          python agent/smoke_test.py
