- name: Run Kiwi smoke test (with retry)
  env:
    RAPIDAPI_KIWI_KEY: ${{ secrets.RAPIDAPI_KIWI_KEY }}
  run: |
    for i in 1 2 3; do
      echo "Attempt $i..."
      python agent/smoke_test_kiwi.py \
        --origin "${{ github.event.inputs.origin }}" \
        --destination "${{ github.event.inputs.destination }}" \
        --startDate "${{ github.event.inputs.startDate }}" \
        --nights "${{ github.event.inputs.nights }}" \
        --adults "${{ github.event.inputs.adults }}" \
        --children "${{ github.event.inputs.children }}" && exit 0
      echo "Attempt $i failed. Retrying in $((i*10)) seconds..."
      sleep $((i*10))
    done
    echo "❌ All attempts failed."
    exit 1
