name: Smoke Test - Amadeus Flights

on:
  workflow_dispatch:
    inputs:
      origin:
        description: "Origin IATA"
        required: false
        default: "EMA"
      destination:
        description: "Destination IATA"
        required: false
        default: "ALC"
      startDate:
        description: "Start date (YYYY-MM-DD)"
        required: false
        default: "2025-08-25"
      nights:
        description: "Nights"
        required: false
        default: "4"
      adults:
        description: "Adults"
        required: false
        default: "2"
      children:
        description: "Children"
        required: false
        default: "0"

jobs:
  amadeus_flights:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flights smoke
        working-directory: agent
        env:
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          AMADEUS_BASE: https://test.api.amadeus.com
        run: |
          python smoke_test_amadeus_flights.py
